AGR-22. Populate agr term.

diff --git a/tools/agriocpp.in b/tools/agriocpp.in
--- a/tools/agriocpp.in
+++ b/tools/agriocpp.in
@@ -1,35 +1,35 @@
 #!/bin/bash
 
-EOSIO_BIN_INSTALL_DIR=`dirname $0`
-if [ "${EOSIO_BIN_INSTALL_DIR}" == "." ]; then
-  EOSIO_BIN_INSTALL_DIR=`pwd`
+AGRIO_BIN_INSTALL_DIR=`dirname $0`
+if [ "${AGRIO_BIN_INSTALL_DIR}" == "." ]; then
+  AGRIO_BIN_INSTALL_DIR=`pwd`
 fi
-EOSIO_INSTALL_DIR=`dirname ${EOSIO_BIN_INSTALL_DIR}`
-if [ -x "@CMAKE_BINARY_DIR@/programs/eosio-abigen/eosio-abigen" ]; then
-    ABIGEN="@CMAKE_BINARY_DIR@/programs/eosio-abigen/eosio-abigen"
-elif [ -x "${EOSIO_INSTALL_DIR}/bin/eosio-abigen" ]; then
-    ABIGEN=${EOSIO_INSTALL_DIR}/bin/eosio-abigen
+AGRIO_INSTALL_DIR=`dirname ${AGRIO_BIN_INSTALL_DIR}`
+if [ -x "@CMAKE_BINARY_DIR@/programs/agrio-abigen/agrio-abigen" ]; then
+    ABIGEN="@CMAKE_BINARY_DIR@/programs/agrio-abigen/agrio-abigen"
+elif [ -x "${AGRIO_INSTALL_DIR}/bin/agrio-abigen" ]; then
+    ABIGEN=${AGRIO_INSTALL_DIR}/bin/agrio-abigen
 fi
-if [ -x "@CMAKE_BINARY_DIR@/externals/binaryen/bin/eosio-s2wasm" ]; then
-    EOSIO_S2WASM="@CMAKE_BINARY_DIR@/externals/binaryen/bin/eosio-s2wasm"
-elif [ -x "${EOSIO_INSTALL_DIR}/bin/eosio-s2wasm" ]; then
-    EOSIO_S2WASM="${EOSIO_INSTALL_DIR}/bin/eosio-s2wasm"
+if [ -x "@CMAKE_BINARY_DIR@/externals/binaryen/bin/agrio-s2wasm" ]; then
+    AGRIO_S2WASM="@CMAKE_BINARY_DIR@/externals/binaryen/bin/agrio-s2wasm"
+elif [ -x "${AGRIO_INSTALL_DIR}/bin/agrio-s2wasm" ]; then
+    AGRIO_S2WASM="${AGRIO_INSTALL_DIR}/bin/agrio-s2wasm"
 else
-    echo "eosio-s2wasm not found either built or installed"
+    echo "agrio-s2wasm not found either built or installed"
     exit 12
 fi
-if [ -x "@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/eosio-wast2wasm" ]; then
-    EOSIO_WAST2WASM="@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/eosio-wast2wasm"
-elif [ -x "${EOSIO_INSTALL_DIR}/bin/eosio-wast2wasm" ]; then
-    EOSIO_WAST2WASM="${EOSIO_INSTALL_DIR}/bin/eosio-wast2wasm"
+if [ -x "@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/agrio-wast2wasm" ]; then
+    AGRIO_WAST2WASM="@CMAKE_BINARY_DIR@/libraries/wasm-jit/Source/Programs/agrio-wast2wasm"
+elif [ -x "${AGRIO_INSTALL_DIR}/bin/agrio-wast2wasm" ]; then
+    AGRIO_WAST2WASM="${AGRIO_INSTALL_DIR}/bin/agrio-wast2wasm"
 else
-    echo "eosio-wast2wasm not found either built or installed"
+    echo "agrio-wast2wasm not found either built or installed"
     exit 14
 fi
 BOOST_INCLUDE_DIR=@Boost_INCLUDE_DIR@
 function copy_skeleton {
     set -e
-    cp -r "${EOSIO_INSTALL_DIR}/share/eosio/skeleton/." $newname
+    cp -r "${AGRIO_INSTALL_DIR}/share/agrio/skeleton/." $newname
 
     for file in $(find ./$newname -name 'skeleton.*')
     do
@@ -68,23 +68,23 @@ function build_contract {
                                    -I @CMAKE_SOURCE_DIR@/contracts/libc++/upstream/include \
                                    -I @CMAKE_SOURCE_DIR@/contracts/musl/upstream/include \
                                    -I @CMAKE_SOURCE_DIR@/externals/magic_get/include \
-                                   -I ${EOSIO_INSTALL_DIR}/include \
-                                   -I${EOSIO_INSTALL_DIR}/include/libc++/upstream/include \
-                                   -I${EOSIO_INSTALL_DIR}/include/musl/upstream/include \
+                                   -I ${AGRIO_INSTALL_DIR}/include \
+                                   -I${AGRIO_INSTALL_DIR}/include/libc++/upstream/include \
+                                   -I${AGRIO_INSTALL_DIR}/include/musl/upstream/include \
                                    -I${BOOST_INCLUDE_DIR} \
                                    -I $filePath \
-                                   ${EOSIOCPP_CFLAGS} \
+                                   ${AGRIOCPP_CFLAGS} \
                                    -c $file -o $workdir/built/$name
         )
 
     done
 
-    declare -a possible_libs=("@CMAKE_BINARY_DIR@/contracts/eosiolib/eosiolib.bc"
+    declare -a possible_libs=("@CMAKE_BINARY_DIR@/contracts/agriolib/agriolib.bc"
                               "@CMAKE_BINARY_DIR@/contracts/libc++/libc++.bc"
                               "@CMAKE_BINARY_DIR@/contracts/musl/libc.bc"
-                              "${EOSIO_INSTALL_DIR}/usr/share/eosio/contractsdk/lib/eosiolib.bc"
-                              "${EOSIO_INSTALL_DIR}/usr/share/eosio/contractsdk/lib/libc++.bc"
-                              "${EOSIO_INSTALL_DIR}/usr/share/eosio/contractsdk/lib/libc.bc")
+                              "${AGRIO_INSTALL_DIR}/usr/share/agrio/contractsdk/lib/agriolib.bc"
+                              "${AGRIO_INSTALL_DIR}/usr/share/agrio/contractsdk/lib/libc++.bc"
+                              "${AGRIO_INSTALL_DIR}/usr/share/agrio/contractsdk/lib/libc.bc")
     declare libs=""
     for lib in "${possible_libs[@]}"; do
         if [ -f "${lib}" ]; then
@@ -93,8 +93,8 @@ function build_contract {
     done
     ($PRINT_CMDS; @WASM_LLVM_LINK@ -only-needed -o $workdir/linked.bc $workdir/built/* ${libs})
     ($PRINT_CMDS; @WASM_LLC@ -thread-model=single --asm-verbose=false -o $workdir/assembly.s $workdir/linked.bc)
-    ($PRINT_CMDS; ${EOSIO_S2WASM} -o $outname -s 16384 $workdir/assembly.s)
-    ($PRINT_CMDS; ${EOSIO_WAST2WASM} $outname ${outname%.*}.wasm -n)
+    ($PRINT_CMDS; ${AGRIO_S2WASM} -o $outname -s 16384 $workdir/assembly.s)
+    ($PRINT_CMDS; ${AGRIO_WAST2WASM} $outname ${outname%.*}.wasm -n)
 
     ($PRINT_CMDS; rm -rf $workdir)
     set +e
@@ -116,11 +116,11 @@ function generate_abi {
         -extra-arg=-I@CMAKE_SOURCE_DIR@/contracts/libc++/upstream/include \
         -extra-arg=-I@CMAKE_SOURCE_DIR@/contracts/musl/upstream/include \
         -extra-arg=-I@CMAKE_SOURCE_DIR@/externals/magic_get/include \
-        -extra-arg=-I${EOSIO_INSTALL_DIR}/include/libc++/upstream/include \
-        -extra-arg=-I${EOSIO_INSTALL_DIR}/include/musl/upstream/include \
+        -extra-arg=-I${AGRIO_INSTALL_DIR}/include/libc++/upstream/include \
+        -extra-arg=-I${AGRIO_INSTALL_DIR}/include/musl/upstream/include \
         -extra-arg=-I${BOOST_INCLUDE_DIR} \
-        -extra-arg=${EOSIOCPP_CFLAGS}  \
-        -extra-arg=-I${EOSIO_INSTALL_DIR}/include -extra-arg=-I$context_folder \
+        -extra-arg=${AGRIOCPP_CFLAGS}  \
+        -extra-arg=-I${AGRIO_INSTALL_DIR}/include -extra-arg=-I$context_folder \
         -extra-arg=-fparse-all-comments -destination-file=${outname} -verbose=0 \
         -context=$context_folder $1 --
 
@@ -152,7 +152,7 @@ function print_help {
 
 function print_deprecation_notice {
     echo -e "\033[0;33mWARNING: this tool is deprecated and will be removed in a future release\033[0m" 1>&2
-    echo -e "\033[0;33mPlease consider using the EOSIO.CDT (https://github.com/EOSIO/eosio.cdt/)\033[0m" 1>&2
+    echo -e "\033[0;33mPlease consider using the AGRIO.CDT (https://github.com/aggregion/agrio.cdt/)\033[0m" 1>&2
 }
 
 command=""
